# Generated by Django 5.1 on 2024-08-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_contact', models.CharField(max_length=15)),
                ('user_age', models.IntegerField()),
                ('user_image', models.ImageField(upload_to='users/')),
                ('User_Status', models.CharField(max_length=50)),
            ],
        ),
    ]
