# Generated by Django 5.1 on 2024-08-21 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
