# Generated by Django 4.2.7 on 2025-01-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_predictionresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predictionresult',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='pdf_file',
            field=models.FileField(default=None, upload_to='prediction_pdfs/'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='predictionresult',
            table=None,
        ),
    ]
